### ISSUE TITLE
进制转换（单字节）在转换八进制时存在问题

### ISSUE THREAD

**Issue by liulyxandy-codemao** [liukuo362573/toolhelper.cn#10]
![image](https://github.com/user-attachments/assets/92947b75-4144-4453-8d25-bff23d02e0c9)

非法的八进制值也可以被转换

复现条件：

- 非法字符不在首位（如 `55@55` , `66668`）

预期输出：

`NaN`

实际输出：

- 省略非法字符之后所有数字（包含非法字符）后的转换值

例：

![image](https://github.com/user-attachments/assets/44f4a315-c174-4f7a-b9fe-2fb57a6e617d)

**Comment by liukuo362573** [comment]
对的，目前是没有限制，8bit 最大值 256 对应的八进制是 400，回头我限制一下这个数，如果大于 400 ，就不能转换。

**Comment by liulyxandy-codemao** [comment]
并且其他任意符号，比如`@`，`#`，`{`在满足条件的情况下都能被插进去

**Comment by liukuo362573** [comment]
> 对的，目前是没有限制，8bit 最大值 256 对应的八进制是 400，回头我限制一下这个数，如果大于 400 ，就不能转换。

@liulyxandy-codemao 修改好了，使用正则做了校验，一开始我以为只能单字节转换，发现多字节转换也不会报错。
[八进制转换](https://www.toolhelper.cn/EncodeDecode/BaseCommon?input=123456%2C11&iFormat=8&iSplit=3&iCustomSplit=&oFormat=16&oSplit=3&oCustomSplit=&output=a72e%2C09)
