### ISSUE TITLE
希望在url参数格式化里面增加一个特殊复制的功能

### ISSUE THREAD

**Issue by wx-yss** [liukuo362573/toolhelper.cn#4]
格式化之后我需要将结果复制到post工具中，我如果直接选中复制，那么参数和值的分隔符为tab符号，这样post工具识别不出，希望增加一个复制按钮，将参数和值以冒号“:”分隔，这个复制之后就可以直接导入到post工具中

**Comment by liukuo362573** [comment]
如果是中文是不是还需要 encodeURIComponent 处理一下的？@wx-yss

**Comment by wx-yss** [comment]
> 如果是中文是不是还需要 encodeURIComponent 处理一下的？@wx-yss

😁 好主意，可以搞一下

**Comment by liukuo362573** [comment]
已增加 复制键值 按钮

**Comment by wx-yss** [comment]
> 已增加 复制键值 按钮

已看到 感谢作者
