### ISSUE TITLE
强烈建议，把“排序”默认设为不选中

### ISSUE THREAD

**Issue by Allens9** [liukuo362573/toolhelper.cn#5]
用户并不喜欢仔细的看各项设置，只能粘贴上原始json, 再复制走格式化好的json。默认选中"排序“，让用户不知不觉间，复制走了排序后的数据，可能导致数组的元素顺序发生变化
而这种变化，对于大量存在的低质量代码，可能会产生严重错误，因为低质量的代码中，往往会写死数据顺序，而是不去数据中搜索需要的元素，重新排序后的json，会让这些代码访问到错误的数组元素

**Comment by liukuo362573** [comment]
好的，排序的初衷是为了方便快速找到需要的 key 值。
