### ISSUE TITLE
帮忙弄个滚动条

### ISSUE THREAD

**Issue by salmanit** [liukuo362573/toolhelper.cn#6]
https://www.toolhelper.cn/Format/XmlFormat
格式化以后，鼠标可以上下滚动，如果横向内容很多的，不太方便横向滚动，得选中文字移动才能看到横向滚动条，是否可以给个checkbox默认一直显示

**Comment by liukuo362573** [comment]
![微信截图_20240321092949](https://github.com/liukuo362573/toolhelper.cn/assets/222744/b963ce04-3903-4798-b194-ed81fbb36af2)
会自动显示水平滚动条，不知道你说的是什么样的情况，能再清楚一些吗？ @salmanit

**Comment by salmanit** [comment]
非常感谢，不清楚之前为啥没有，现在是好的。
