### ISSUE TITLE
建议添加 gzip 在 编码与解码 中

### ISSUE THREAD

**Issue by HundSimon** [liukuo362573/toolhelper.cn#7]
如题

**Comment by liukuo362573** [comment]
@HundSimon ，Hi，gzip 的数据，你想怎么输入到文本框里呢，是十六进制吗？

**Comment by HundSimon** [comment]
输入base64的压缩数据，然后解压缩
就像这样的 https://www.zickty.com/texttogzip

**Comment by liukuo362573** [comment]
好的，近期我添加一下。

**Comment by liukuo362573** [comment]
> 输入base64的压缩数据，然后解压缩 就像这样的 https://www.zickty.com/texttogzip

压缩与解压缩功能已增加，感谢反馈哈，[https://www.toolhelper.cn/EncodeDecode/Compress](https://www.toolhelper.cn/EncodeDecode/Compress)

**Comment by HundSimon** [comment]
感谢！
