### ISSUE TITLE
进制转换，16进制无法补0

### ISSUE THREAD

**Issue by forever-knight** [liukuo362573/toolhelper.cn#9]
https://www.toolhelper.cn/EncodeDecode/BaseCommon

老版本10进制数组转16进制数组，是可以补0的（补齐一个byte，比如0x01，现在只能0x1）。
新版本虽然更灵活，但这个功能丢失了。

**Comment by liukuo362573** [comment]
@forever-knight  Hi，已修改，现在默认十六进制数总共 2 位，二进制数总共 8 位，前面不足就补 0 ，八进制数貌似不需要补0。

[参考链接](https://www.toolhelper.cn/EncodeDecode/BaseCommon?input=1%2C2%2C3%2C4%2C5%2C6%2C7%2C8&iFormat=10&iSplit=3&iCustomSplit=&oFormat=16&oSplit=4&oCustomSplit=%2C0x&output=0x01%2C0x02%2C0x03%2C0x04%2C0x05%2C0x06%2C0x07%2C0x08)
